### ISSUE TITLE
macOS Support?

### ISSUE THREAD

**Issue by koudelka** [aws/clock-bound#30]
Hi friends, it seems that recent versions of clock-bound no longer compile on macOS. :(

```
❯ cargo run --features="daemon"            
   Compiling clock-bound v3.0.0-alpha.0 (/Users/mikes/repos/clock-bound/clock-bound)
error[E0432]: unresolved import `libc::ADJ_SETOFFSET`
 --> clock-bound/src/daemon/time/timex.rs:6:5
  |
6 |     ADJ_SETOFFSET, MOD_FREQUENCY, MOD_NANO, MOD_OFFSET, MOD_STATUS, MOD_TIMECONST, STA_FREQHOLD,
  |     ^^^^^^^^^^^^^ no `ADJ_SETOFFSET` in the root

```

I'm not a rust developer, but I poked around a bit, and as far as I can tell, that constant isn't present on a mac.

**Comment by jrid** [comment]
You are correct and a few compilation flags are missing to have ClockBound build on MacOS, as it used to.

We will address that in the next point release.

**Comment by rluu** [comment]
@koudelka , yes, the build is not working for MacOS on the `main` branch which is tracking the v3.0.0 alpha version.  If you have an immediate need for a working build on MacOS, we have the ClockBound v2.0 version on the `main-2.0` branch:

- https://github.com/aws/clock-bound/tree/main-2.0

**Comment by koudelka** [comment]
most helpful, thanks! :)
